import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * The admin's import map, and the blank page it caused.
 *
 * Payload resolves every admin component through
 * `src/app/(payload)/admin/importMap.js` — a file **generated by
 * `pnpm payload:importmap` and committed**. If the running config asks for a
 * component the map does not carry, the admin renders **nothing**: no error, no
 * message, a white screen to whoever opened `/admin`.
 *
 * That is what happened. `storagePlugins()` returned `[]` when R2 was
 * unconfigured, so locally the S3 plugin never loaded and the generated map had
 * no entry for its `S3ClientUploadHandler`. Production had the four R2
 * variables, loaded the plugin, and broke. The plugin registers that component
 * whether or not it is enabled, precisely "to avoid import map discrepancies
 * between dev and prod" — we were the discrepancy.
 *
 * Two things are asserted here, and the second is the one that matters:
 *
 * 1. Every component the config declares is present in the committed map.
 * 2. **The config declares the same components with and without R2 set.** An
 *    admin whose shape depends on the environment makes a committed, generated
 *    file correct on one machine and wrong on another, and the symptom is
 *    invisible until somebody opens the admin in production.
 */

const R2_VARS = ['R2_ACCOUNT_ID', 'R2_BUCKET', 'R2_ACCESS_KEY_ID', 'R2_SECRET_ACCESS_KEY'] as const

const MAP_SOURCE = readFileSync(
  join(process.cwd(), 'src/app/(payload)/admin/importMap.js'),
  'utf8',
)

/** Every `path#export` key the generated map can resolve. */
function mappedComponents(): Set<string> {
  const keys = [...MAP_SOURCE.matchAll(/"([^"]+#[^"]+)":/g)]
    .map((match) => match[1])
    .filter((key): key is string => typeof key === 'string')
  return new Set(keys)
}

/**
 * Every component path the config asks for.
 *
 * Read out of the built config rather than from a list here, so a new custom
 * view or a new plugin is covered without anybody remembering to add it.
 */
async function declaredComponents(): Promise<Set<string>> {
  // Imported fresh each time: the config is built at module scope, so reading
  // it twice with different environments needs the module cache reset.
  const { default: configPromise } = await import(
    /* @vite-ignore */ `${join(process.cwd(), 'payload.config.ts')}?t=${Math.random()}`
  )
  const config = await configPromise

  const found = new Set<string>()
  for (const path of Object.keys(config.admin?.dependencies ?? {})) found.add(path)
  for (const provider of config.admin?.components?.providers ?? []) {
    found.add(typeof provider === 'string' ? provider : provider.path)
  }
  for (const entry of config.admin?.components?.beforeNavLinks ?? []) {
    found.add(typeof entry === 'string' ? entry : entry.path)
  }
  for (const view of Object.values(config.admin?.components?.views ?? {})) {
    const component = (view as { Component?: unknown }).Component
    if (typeof component === 'string') found.add(component)
  }
  return found
}

function withR2<T>(present: boolean, run: () => Promise<T>): Promise<T> {
  const saved = R2_VARS.map((name) => [name, process.env[name]] as const)
  for (const name of R2_VARS) {
    if (present) process.env[name] = 'test-value'
    else delete process.env[name]
  }
  return run().finally(() => {
    for (const [name, value] of saved) {
      if (value === undefined) delete process.env[name]
      else process.env[name] = value
    }
  })
}

describe('the admin import map', () => {
  it('carries the S3 upload handler', async () => {
    // Named explicitly as well as covered by the sweep below, because this is
    // the one that actually broke and the message should say so.
    expect(mappedComponents()).toContain('@payloadcms/storage-s3/client#S3ClientUploadHandler')
  })

  it('carries every component the config declares, with R2 configured', async () => {
    const declared = await withR2(true, declaredComponents)
    const mapped = mappedComponents()

    const missing = [...declared].filter((path) => !mapped.has(path))
    expect(
      missing,
      `Missing from importMap.js — the admin renders blank. Run: pnpm payload:importmap`,
    ).toEqual([])
  })

  /**
   * The root cause, stated as a property. If this fails, somebody has made an
   * admin component conditional on the environment again, and the committed map
   * is about to be right on one machine and wrong on another.
   */
  it('declares the same components whether or not R2 is configured', async () => {
    const configured = [...(await withR2(true, declaredComponents))].sort()
    const unconfigured = [...(await withR2(false, declaredComponents))].sort()

    expect(unconfigured).toEqual(configured)
  })
})
