/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    cities: City;
    universities: University;
    colleges: College;
    stages: Stage;
    'treatment-types': TreatmentType;
    'stage-capabilities': StageCapability;
    'student-documents': StudentDocument;
    'case-photos': CasePhoto;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    universities: UniversitiesSelect<false> | UniversitiesSelect<true>;
    colleges: CollegesSelect<false> | CollegesSelect<true>;
    stages: StagesSelect<false> | StagesSelect<true>;
    'treatment-types': TreatmentTypesSelect<false> | TreatmentTypesSelect<true>;
    'stage-capabilities': StageCapabilitiesSelect<false> | StageCapabilitiesSelect<true>;
    'student-documents': StudentDocumentsSelect<false> | StudentDocumentsSelect<true>;
    'case-photos': CasePhotosSelect<false> | CasePhotosSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  fullName: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  nameAr: string;
  /**
   * المعرّف الثابت (بالإنكليزي، بدون مسافات). لا تغيّره بعد ما تنربط بيه حالات — راح تنفصل عنه.
   */
  slug: string;
  /**
   * إذا مطفي، ما يظهر بالخيارات الجديدة — بس الحالات القديمة تبقى.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "universities".
 */
export interface University {
  id: number;
  nameAr: string;
  /**
   * المعرّف الثابت (بالإنكليزي، بدون مسافات). لا تغيّره بعد ما تنربط بيه حالات — راح تنفصل عنه.
   */
  slug: string;
  city: number | City;
  /**
   * إذا مطفي، ما يظهر بالخيارات الجديدة — بس الحالات القديمة تبقى.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colleges".
 */
export interface College {
  id: number;
  nameAr: string;
  /**
   * المعرّف الثابت (بالإنكليزي، بدون مسافات). لا تغيّره بعد ما تنربط بيه حالات — راح تنفصل عنه.
   */
  slug: string;
  university: number | University;
  /**
   * إذا مطفي، ما يظهر بالخيارات الجديدة — بس الحالات القديمة تبقى.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stages".
 */
export interface Stage {
  id: number;
  nameAr: string;
  /**
   * المعرّف الثابت (بالإنكليزي، بدون مسافات). لا تغيّره بعد ما تنربط بيه حالات — راح تنفصل عنه.
   */
  slug: string;
  order: number;
  /**
   * شنو تكدر تعالج هذي المرحلة بشكل عام. تنطبق على أي عيادة ما محدد إلها صلاحيات خاصة. بدون هذا، إضافة عيادة جديدة تخلي كل الحالات مخفية عن طلابها لحد ما أحد يملي الجدول.
   */
  defaultTreatmentTypes?: (number | TreatmentType)[] | null;
  /**
   * إذا مطفي، ما يظهر بالخيارات الجديدة — بس الحالات القديمة تبقى.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treatment-types".
 */
export interface TreatmentType {
  id: number;
  nameAr: string;
  /**
   * المعرّف الثابت (بالإنكليزي، بدون مسافات). لا تغيّره بعد ما تنربط بيه حالات — راح تنفصل عنه.
   */
  slug: string;
  order: number;
  /**
   * إذا مطفي، ما يظهر بالخيارات الجديدة — بس الحالات القديمة تبقى.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * شنو تكدر تعالج كل مرحلة بكل عيادة. هذا يحدد شنو يشوف الطالب.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stage-capabilities".
 */
export interface StageCapability {
  id: number;
  label?: string | null;
  college: number | College;
  stage: number | Stage;
  treatmentTypes: (number | TreatmentType)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * وثائق تسجيل الطلبة. للمراجعة فقط.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-documents".
 */
export interface StudentDocument {
  id: number;
  /**
   * ملاحظات داخلية. ما تظهر للطالب.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * صور داخل الفم. للمراجعة والحذف فقط.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-photos".
 */
export interface CasePhoto {
  id: number;
  /**
   * ملاحظات داخلية. ما تظهر للمريض ولا للطالب.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'universities';
        value: number | University;
      } | null)
    | ({
        relationTo: 'colleges';
        value: number | College;
      } | null)
    | ({
        relationTo: 'stages';
        value: number | Stage;
      } | null)
    | ({
        relationTo: 'treatment-types';
        value: number | TreatmentType;
      } | null)
    | ({
        relationTo: 'stage-capabilities';
        value: number | StageCapability;
      } | null)
    | ({
        relationTo: 'student-documents';
        value: number | StudentDocument;
      } | null)
    | ({
        relationTo: 'case-photos';
        value: number | CasePhoto;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  fullName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  nameAr?: T;
  slug?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "universities_select".
 */
export interface UniversitiesSelect<T extends boolean = true> {
  nameAr?: T;
  slug?: T;
  city?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colleges_select".
 */
export interface CollegesSelect<T extends boolean = true> {
  nameAr?: T;
  slug?: T;
  university?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stages_select".
 */
export interface StagesSelect<T extends boolean = true> {
  nameAr?: T;
  slug?: T;
  order?: T;
  defaultTreatmentTypes?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treatment-types_select".
 */
export interface TreatmentTypesSelect<T extends boolean = true> {
  nameAr?: T;
  slug?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stage-capabilities_select".
 */
export interface StageCapabilitiesSelect<T extends boolean = true> {
  label?: T;
  college?: T;
  stage?: T;
  treatmentTypes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-documents_select".
 */
export interface StudentDocumentsSelect<T extends boolean = true> {
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-photos_select".
 */
export interface CasePhotosSelect<T extends boolean = true> {
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * كم ساعة عند الطالب حتى يتواصل وية المريض بعد ما ياخذ الحالة. إذا انتهت المهلة، الحالة ترجع للقائمة لطالب ثاني. الافتراضي 48 ساعة — الطلبة بالعيادة أثناء النهار والمريض ممكن ما يرد أول مرة.
   */
  contactWindowHours: number;
  /**
   * إذا مرت هذي المدة وما حجز أي طالب الحالة، تنتهي صلاحيتها وتنشال من القائمة. المريض غالباً يكون لكه علاج بمكان ثاني، وما نريد طالب يتصل بيه بعد شهور.
   */
  caseExpiryDays: number;
  /**
   * لما الطالب يبلّغ إنه اتصل بالمريض، نمدد مهلته هذي المدة حتى ننطي المريض وقت يأكد. مريض ما يستعمل تلگرام وما يفتح الرابط ممكن ياخذ يومين لحد ما يرد. الافتراضي 48 ساعة.
   */
  contactGraceHours: number;
  /**
   * إذا طالب بلّغ إن صاحب الرقم ما طلب علاج، الرقم ما يكدر يقدّم حالة جديدة هذي المدة. هذا يمنع نفس الشخص من إعادة إرسال نفس الطلب على رقم شخص ما يعرف. تكدر تشيل الإيقاف من صفحة الحالات.
   */
  wrongNumberBlockDays: number;
  /**
   * أكثر من واحد بنفس البيت ممكن يستعملون نفس الرقم، فما نخليها وحدة — بس نمنع إن أحد يرسل عشرات الطلبات على رقم شخص ثاني.
   */
  maxOpenCasesPerPhone: number;
  /**
   * حد إضافي على السرعة، مو بس على العدد المفتوح.
   */
  maxCasesPerPhonePerDay: number;
  /**
   * بعد هذي المدة، اسم المريض ورقمه وملاحظاته تنمحى نهائياً من الحالة. الحالة نفسها تبقى — رمزها وسجلها ونوع العلاج — حتى تكدر تجاوب إذا أحد سأل عن حالة قديمة. رقم الموبايل هو أخطر شي بالنظام، وحالة خالصة ما تحتاجه.
   */
  contactRetentionDays: number;
  /**
   * بعد ما تنغلق الحالة، الصور تنحذف نهائياً بعد هذي المدة. ما نحتفظ بصور داخل فم المريض أكثر من اللازم.
   */
  photoRetentionDays: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  contactWindowHours?: T;
  caseExpiryDays?: T;
  contactGraceHours?: T;
  wrongNumberBlockDays?: T;
  maxOpenCasesPerPhone?: T;
  maxCasesPerPhonePerDay?: T;
  contactRetentionDays?: T;
  photoRetentionDays?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}