import type { CollectionConfig } from 'payload'
import { isAdmin } from '@/payload/access'

/**
 * Intraoral photographs, stored.
 *
 * Nothing here is publicly readable and nothing is served from `/public`. These
 * are pictures inside a patient's mouth: `read` is limited to logged-in admins,
 * so Payload's own file route is admin-only, and students and patients are
 * served through `/api/case-photos/[id]`, which re-checks who is asking on every
 * request.
 *
 * Only WebP is accepted because everything is re-encoded before it gets here —
 * which is also what removes the EXIF, and with it the GPS coordinates a phone
 * writes into a photograph.
 */
export const CasePhotos: CollectionConfig = {
  slug: 'case-photos',
  labels: { singular: 'صورة حالة', plural: 'صور الحالات' },
  admin: {
    useAsTitle: 'filename',
    group: 'الإدارة',
    description: 'صور داخل الفم. للمراجعة والحذف فقط.',
  },

  access: {
    read: isAdmin,
    // Created only through the Local API, from the submission path that has
    // already processed and stripped the image.
    create: () => false,
    update: isAdmin,
    // Admins can remove any image.
    delete: isAdmin,
  },

  upload: {
    staticDir: 'uploads/case-photos',
    mimeTypes: ['image/webp'],
    filesRequiredOnCreate: true,

    /**
     * A thumbnail, because the grid on a case shows these at about 170px wide on
     * a phone and was sending the full 1600px file to fill it. Measured on Slow
     * 3G with the CPU throttled: a case with photographs took 23 seconds to
     * load, against under 5 for every other page. The median user is on exactly
     * that connection.
     *
     * Generated by sharp from the already-processed WebP, so it inherits the
     * stripped metadata rather than re-reading the original upload.
     */
    imageSizes: [
      {
        name: 'thumb',
        width: 480,
        height: undefined,
        withoutEnlargement: true,
        formatOptions: { format: 'webp', options: { quality: 70 } },
      },
    ],
  },

  fields: [
    {
      name: 'note',
      type: 'textarea',
      label: 'ملاحظة الإدارة',
      admin: { description: 'ملاحظات داخلية. ما تظهر للمريض ولا للطالب.' },
    },
  ],
}
